const parks = [
  {
    key: "BAL03",
    name: "Oriole Park I",
    city: "Baltimore",
    state: "MD",
    country: "US",
  },
  {
    key: "BAL06",
    name: "Oriole Park II",
    city: "Baltimore",
    state: "MD",
    country: "US",
  },
  {
    key: "BUF03",
    name: "Olympic Park II",
    city: "Buffalo",
    state: "NY",
    country: "US",
  },
  {
    key: "BAL01",
    name: "Madison Avenue Grounds",
    city: "Baltimore",
    state: "MD",
    country: "US",
  },
  {
    key: "BOS06",
    name: "Huntington Avenue Baseball Grounds",
    city: "Boston",
    state: "MA",
    country: "US",
  },
  {
    key: "ANA01",
    name: "Angel Stadium of Anaheim",
    city: "Anaheim",
    state: "CA",
    country: "US",
  },
  {
    key: "CHI11",
    name: "Wrigley Field",
    city: "Chicago",
    state: "IL",
    country: "US",
  },
  {
    key: "CIN05",
    name: "League Park II",
    city: "Cincinnati",
    state: "OH",
    country: "US",
  },
  {
    key: "COV01",
    name: "Star Baseball Park",
    city: "Covington",
    state: "KY",
    country: "US",
  },
  {
    key: "HAR01",
    name: "Harrison Field",
    city: "Harrison",
    state: "NJ",
    country: "US",
  },
  {
    key: "LOS01",
    name: "Los Angeles Memorial Coliseum",
    city: "Los Angeles",
    state: "CA",
    country: "US",
  },
  {
    key: "LUD01",
    name: "Ludlow Baseball Park",
    city: "Ludlow",
    state: "KY",
    country: "US",
  },
  {
    key: "NYC02",
    name: "Capitoline Grounds",
    city: "Brooklyn",
    state: "NY",
    country: "US",
  },
  {
    key: "PIT06",
    name: "Forbes Field",
    city: "Pittsburgh",
    state: "PA",
    country: "US",
  },
  {
    key: "TOR02",
    name: "Rogers Centre",
    city: "Toronto",
    state: "ON",
    country: "CA",
  },
  {
    key: "WAS05",
    name: "Swampoodle Grounds",
    city: "Washington",
    state: "DC",
    country: "US",
  },
  {
    key: "WAS09",
    name: "Griffith Stadium",
    city: "Washington",
    state: "DC",
    country: "US",
  },
  {
    key: "BOS01",
    name: "South End Grounds I",
    city: "Boston",
    state: "MA",
    country: "US",
  },
  {
    key: "CIN01",
    name: "Lincoln Park Grounds",
    city: "Cincinnati",
    state: "OH",
    country: "US",
  },
  {
    key: "CLE04",
    name: "Brotherhood Park",
    city: "Cleveland",
    state: "OH",
    country: "US",
  },
  {
    key: "DEN01",
    name: "Mile High Stadium",
    city: "Denver",
    state: "CO",
    country: "US",
  },
  {
    key: "DET05",
    name: "Comerica Park",
    city: "Detroit",
    state: "MI",
    country: "US",
  },
  {
    key: "IND01",
    name: "South Street Park",
    city: "Indianapolis",
    state: "IN",
    country: "US",
  },
  {
    key: "MIL06",
    name: "Miller Park",
    city: "Milwaukee",
    state: "WI",
    country: "US",
  },
  {
    key: "NEW01",
    name: "Howard Avenue Grounds",
    city: "New Haven",
    state: "CT",
    country: "US",
  },
  {
    key: "NYC07",
    name: "Grauer's Ridgewood Park",
    city: "Queens",
    state: "NY",
    country: "US",
  },
  {
    key: "NYC20",
    name: "Citi Field",
    city: "New York",
    state: "NY",
    country: "US",
  },
  {
    key: "SAI01",
    name: "St. George Cricket Grounds",
    city: "New York",
    state: "NY",
    country: "US",
  },
  {
    key: "WAR01",
    name: "Rocky Point Park",
    city: "Warwick",
    state: "RI",
    country: "US",
  },
  {
    key: "WAS08",
    name: "American League Park II",
    city: "Washington",
    state: "DC",
    country: "US",
  },
  {
    key: "WEE01",
    name: "Monitor Grounds",
    city: "Weehawken",
    state: "NJ",
    country: "US",
  },
  {
    key: "CAN01",
    name: "Mahaffey Park",
    city: "Canton",
    state: "OH",
    country: "US",
  },
  {
    key: "CHI06",
    name: "West Side Park",
    city: "Chicago",
    state: "IL",
    country: "US",
  },
  {
    key: "CLE03",
    name: "League Park II",
    city: "Cleveland",
    state: "OH",
    country: "US",
  },
  {
    key: "IND05",
    name: "Seventh Street Park III",
    city: "Indianapolis",
    state: "IN",
    country: "US",
  },
  {
    key: "LAS01",
    name: "Cashman Field",
    city: "Las Vegas",
    state: "NV",
    country: "US",
  },
  {
    key: "MIL03",
    name: "Athletic Park",
    city: "Milwaukee",
    state: "WI",
    country: "US",
  },
  {
    key: "NYC03",
    name: "Polo Grounds I (Southeast Diamond)",
    city: "New York",
    state: "NY",
    country: "US",
  },
  {
    key: "NYC05",
    name: "Washington Park I",
    city: "Brooklyn",
    state: "NY",
    country: "US",
  },
  {
    key: "NYC10",
    name: "Polo Grounds IV",
    city: "New York",
    state: "NY",
    country: "US",
  },
  {
    key: "NYC14",
    name: "Polo Grounds V",
    city: "New York",
    state: "NY",
    country: "US",
  },
  {
    key: "PHI05",
    name: "Keystone Park",
    city: "Philadelphia",
    state: "PA",
    country: "US",
  },
  {
    key: "PIT03",
    name: "Exposition Park II",
    city: "Pittsburgh",
    state: "PA",
    country: "US",
  },
  {
    key: "PRO01",
    name: "Adelaide Avenue Grounds",
    city: "Providence",
    state: "RI",
    country: "US",
  },
  {
    key: "BAL11",
    name: "Memorial Stadium",
    city: "Baltimore",
    state: "MD",
    country: "US",
  },
  {
    key: "BOS05",
    name: "South End Grounds III",
    city: "Boston",
    state: "MA",
    country: "US",
  },
  {
    key: "CIN03",
    name: "Bank Street Grounds",
    city: "Cincinnati",
    state: "OH",
    country: "US",
  },
  {
    key: "CIN04",
    name: "League Park I",
    city: "Cincinnati",
    state: "OH",
    country: "US",
  },
  {
    key: "COL01",
    name: "Recreation Park I",
    city: "Columbus",
    state: "OH",
    country: "US",
  },
  {
    key: "DEN02",
    name: "Coors Field",
    city: "Denver",
    state: "CO",
    country: "US",
  },
  {
    key: "FTB01",
    name: "Fort Bragg Field",
    city: "Fort Bragg",
    state: "NC",
    country: "US",
  },
  {
    key: "GLO02",
    name: "Gloucester Fireworks Park",
    city: "Gloucester City",
    state: "NJ",
    country: "US",
  },
  {
    key: "MON01",
    name: "Parc Jarry",
    city: "Montreal",
    state: "QC",
    country: "CA",
  },
  {
    key: "PHI02",
    name: "Centennial Park",
    city: "Philadelphia",
    state: "PA",
    country: "US",
  },
  {
    key: "PHI08",
    name: "University of Penn. Athletic Field",
    city: "Philadelphia",
    state: "PA",
    country: "US",
  },
  {
    key: "PHI11",
    name: "Shibe Park",
    city: "Philadelphia",
    state: "PA",
    country: "US",
  },
  {
    key: "PHI13",
    name: "Citizens Bank Park",
    city: "Philadelphia",
    state: "PA",
    country: "US",
  },
  {
    key: "PHI14",
    name: "Huntingdon Grounds II",
    city: "Philadelphia",
    state: "PA",
    country: "US",
  },
  {
    key: "PIT08",
    name: "PNC Park",
    city: "Pittsburgh",
    state: "PA",
    country: "US",
  },
  {
    key: "SYD01",
    name: "Sydney Cricket Ground",
    city: "Sydney",
    state: "New South Wales",
    country: "AU",
  },
  {
    key: "THR01",
    name: "Three Rivers Park",
    city: "Three Rivers",
    state: "NY",
    country: "US",
  },
  {
    key: "CIN06",
    name: "Palace of the Fans",
    city: "Cincinnati",
    state: "OH",
    country: "US",
  },
  {
    key: "CLE06",
    name: "League Park IV",
    city: "Cleveland",
    state: "OH",
    country: "US",
  },
  {
    key: "DET01",
    name: "Recreation Park",
    city: "Detroit",
    state: "MI",
    country: "US",
  },
  {
    key: "GLO01",
    name: "Gloucester Point Grounds",
    city: "Gloucester City",
    state: "NJ",
    country: "US",
  },
  {
    key: "LOU01",
    name: "Louisville Baseball Park",
    city: "Louisville",
    state: "KY",
    country: "US",
  },
  {
    key: "MIA02",
    name: "Marlins Park",
    city: "Miami",
    state: "FL",
    country: "US",
  },
  {
    key: "MIL01",
    name: "Milwaukee Base-Ball Grounds",
    city: "Milwaukee",
    state: "WI",
    country: "US",
  },
  {
    key: "MIL04",
    name: "Lloyd Street Grounds",
    city: "Milwaukee",
    state: "WI",
    country: "US",
  },
  {
    key: "MIN04",
    name: "Target Field",
    city: "Minneapolis",
    state: "MN",
    country: "US",
  },
  {
    key: "MNT01",
    name: "Estadio Monterrey",
    city: "Monterrey",
    state: "Nuevo Leon",
    country: "MX",
  },
  {
    key: "NWK01",
    name: "Wiedenmeyer's Park",
    city: "Newark",
    state: "NJ",
    country: "US",
  },
  {
    key: "NYC01",
    name: "Union Grounds",
    city: "Brooklyn",
    state: "NY",
    country: "US",
  },
  {
    key: "OMA01",
    name: "TD Ameritrade Park",
    city: "Omaha",
    state: "NE",
    country: "US",
  },
  {
    key: "BOS07",
    name: "Fenway Park",
    city: "Boston",
    state: "MA",
    country: "US",
  },
  {
    key: "PIT04",
    name: "Recreation Park",
    city: "Pittsburgh",
    state: "PA",
    country: "US",
  },
  {
    key: "BOS08",
    name: "Braves Field",
    city: "Boston",
    state: "MA",
    country: "US",
  },
  {
    key: "CLE01",
    name: "National Association Grounds",
    city: "Cleveland",
    state: "OH",
    country: "US",
  },
  {
    key: "CLL01",
    name: "Euclid Beach Park",
    city: "Collinwood",
    state: "OH",
    country: "US",
  },
  {
    key: "COL04",
    name: "Neil Park II",
    city: "Columbus",
    state: "OH",
    country: "US",
  },
  {
    key: "DET03",
    name: "Burns Park",
    city: "Detroit",
    state: "MI",
    country: "US",
  },
  {
    key: "FOR01",
    name: "Grand Duchess",
    city: "Fort Wayne",
    state: "IN",
    country: "US",
  },
  {
    key: "GRA01",
    name: "Ramona Park",
    city: "Grand Rapids",
    state: "MI",
    country: "US",
  },
  {
    key: "HRT02",
    name: "Hartford Trotting Park",
    city: "Hartford",
    state: "CT",
    country: "US",
  },
  {
    key: "IND03",
    name: "Bruce Grounds",
    city: "Indianapolis",
    state: "IN",
    country: "US",
  },
  {
    key: "LON01",
    name: "London Stadium",
    city: "London",
    state: "ENG",
    country: "UK",
  },
  {
    key: "NYC04",
    name: "Polo Grounds II (Southwest Diamond)",
    city: "New York",
    state: "NY",
    country: "US",
  },
  {
    key: "NYC13",
    name: "Hilltop Park",
    city: "New York",
    state: "NY",
    country: "US",
  },
  {
    key: "PEN01",
    name: "East End Park",
    city: "Cincinnati",
    state: "OH",
    country: "US",
  },
  {
    key: "PHI06",
    name: "Huntingdon Grounds I",
    city: "Philadelphia",
    state: "PA",
    country: "US",
  },
  {
    key: "PHI10",
    name: "Columbia Park",
    city: "Philadelphia",
    state: "PA",
    country: "US",
  },
  {
    key: "PHI12",
    name: "Veterans Stadium",
    city: "Philadelphia",
    state: "PA",
    country: "US",
  },
  {
    key: "SFO03",
    name: "AT&T Park",
    city: "San Francisco",
    state: "CA",
    country: "US",
  },
  {
    key: "WAS06",
    name: "Boundary Field",
    city: "Washington",
    state: "DC",
    country: "US",
  },
  {
    key: "WIL02",
    name: "BB&T Ballpark at Bowman Field",
    city: "Williamsport",
    state: "PA",
    country: "US",
  },
  {
    key: "BOS03",
    name: "South End Grounds II",
    city: "Boston",
    state: "MA",
    country: "US",
  },
  {
    key: "BOS04",
    name: "Congress Street Grounds",
    city: "Boston",
    state: "MA",
    country: "US",
  },
  {
    key: "CHI10",
    name: "Comiskey Park I",
    city: "Chicago",
    state: "IL",
    country: "US",
  },
  {
    key: "CIN02",
    name: "Avenue Grounds",
    city: "Cincinnati",
    state: "OH",
    country: "US",
  },
  {
    key: "COL02",
    name: "Recreation Park II",
    city: "Columbus",
    state: "OH",
    country: "US",
  },
  {
    key: "HRT01",
    name: "Hartford Ball Club Grounds",
    city: "Hartford",
    state: "CT",
    country: "US",
  },
  {
    key: "IND07",
    name: "Federal League Park",
    city: "Indianapolis",
    state: "IN",
    country: "US",
  },
  {
    key: "KEO01",
    name: "Perry Park",
    city: "Keokuk",
    state: "IA",
    country: "US",
  },
  {
    key: "MIL02",
    name: "Wright Street Grounds",
    city: "Milwaukee",
    state: "WI",
    country: "US",
  },
  {
    key: "MIN03",
    name: "Hubert H. Humphrey Metrodome",
    city: "Minneapolis",
    state: "MN",
    country: "US",
  },
  {
    key: "PHI04",
    name: "Recreation Park",
    city: "Philadelphia",
    state: "PA",
    country: "US",
  },
  {
    key: "PHI07",
    name: "Forepaugh Park",
    city: "Philadelphia",
    state: "PA",
    country: "US",
  },
  {
    key: "ROC02",
    name: "Culver Field II",
    city: "Rochester",
    state: "NY",
    country: "US",
  },
  {
    key: "STL08",
    name: "Handlan's Park",
    city: "St. Louis",
    state: "MO",
    country: "US",
  },
  {
    key: "SYR01",
    name: "Star Park I",
    city: "Syracuse",
    state: "NY",
    country: "US",
  },
  {
    key: "TOL02",
    name: "Tri-State Fair Grounds",
    city: "Toledo",
    state: "OH",
    country: "US",
  },
  {
    key: "WAS04",
    name: "Athletic Park",
    city: "Washington",
    state: "DC",
    country: "US",
  },
  {
    key: "IND02",
    name: "Seventh Street Park I",
    city: "Indianapolis",
    state: "IN",
    country: "US",
  },
  {
    key: "ALT01",
    name: "Columbia Park",
    city: "Altoona",
    state: "PA",
    country: "US",
  },
  {
    key: "IND04",
    name: "Seventh Street Park II",
    city: "Indianapolis",
    state: "IN",
    country: "US",
  },
  {
    key: "LOU02",
    name: "Eclipse Park I",
    city: "Louisville",
    state: "KY",
    country: "US",
  },
  {
    key: "LOU04",
    name: "Eclipse Park III",
    city: "Louisville",
    state: "KY",
    country: "US",
  },
  {
    key: "MIA01",
    name: "Sun Life Stadium",
    city: "Miami",
    state: "FL",
    country: "US",
  },
  {
    key: "MON02",
    name: "Stade Olympique",
    city: "Montreal",
    state: "QC",
    country: "CA",
  },
  {
    key: "NYC09",
    name: "Polo Grounds III",
    city: "New York",
    state: "NY",
    country: "US",
  },
  {
    key: "PIT01",
    name: "Union Park",
    city: "Pittsburgh",
    state: "PA",
    country: "US",
  },
  {
    key: "STL06",
    name: "Sportsman's Park II",
    city: "St. Louis",
    state: "MO",
    country: "US",
  },
  {
    key: "WHE01",
    name: "Island Grounds",
    city: "Wheeling",
    state: "WV",
    country: "US",
  },
  {
    key: "WIL01",
    name: "Union Street Park",
    city: "Wilmington",
    state: "DE",
    country: "US",
  },
  {
    key: "ARL01",
    name: "Arlington Stadium",
    city: "Arlington",
    state: "TX",
    country: "US",
  },
  {
    key: "ARL02",
    name: "Rangers Ballpark in Arlington",
    city: "Arlington",
    state: "TX",
    country: "US",
  },
  {
    key: "BAL05",
    name: "Monumental Park",
    city: "Baltimore",
    state: "MD",
    country: "US",
  },
  {
    key: "CHI09",
    name: "South Side Park III",
    city: "Chicago",
    state: "IL",
    country: "US",
  },
  {
    key: "CIN07",
    name: "Crosley Field",
    city: "Cincinnati",
    state: "OH",
    country: "US",
  },
  {
    key: "CLE02",
    name: "League Park I",
    city: "Cleveland",
    state: "OH",
    country: "US",
  },
  {
    key: "DAY01",
    name: "Fairview Park",
    city: "Dayton",
    state: "OH",
    country: "US",
  },
  {
    key: "HOB01",
    name: "Elysian Field",
    city: "Hoboken",
    state: "NJ",
    country: "US",
  },
  {
    key: "LOS02",
    name: "Wrigley Field",
    city: "Los Angeles",
    state: "CA",
    country: "US",
  },
  {
    key: "LOS03",
    name: "Dodger Stadium",
    city: "Los Angeles",
    state: "CA",
    country: "US",
  },
  {
    key: "NEW02",
    name: "Hamilton Park",
    city: "New Haven",
    state: "CT",
    country: "US",
  },
  {
    key: "NYC08",
    name: "Washington Park II",
    city: "Brooklyn",
    state: "NY",
    country: "US",
  },
  {
    key: "PHO01",
    name: "Chase Field",
    city: "Phoenix",
    state: "AZ",
    country: "US",
  },
  {
    key: "STL04",
    name: "Union Grounds",
    city: "St. Louis",
    state: "MO",
    country: "US",
  },
  {
    key: "TOK01",
    name: "Tokyo Dome",
    city: "Tokyo",
    state: "Tokyo",
    country: "JP",
  },
  {
    key: "WAS11",
    name: "Nationals Park",
    city: "Washington",
    state: "DC",
    country: "US",
  },
  {
    key: "KAN03",
    name: "Exposition Park",
    city: "Kansas City",
    state: "MO",
    country: "US",
  },
  {
    key: "MIL05",
    name: "County Stadium",
    city: "Milwaukee",
    state: "WI",
    country: "US",
  },
  {
    key: "NEW03",
    name: "Geauga Lake Grounds",
    city: "Geauga Lake",
    state: "OH",
    country: "US",
  },
  {
    key: "NYC11",
    name: "Eastern Park",
    city: "Brooklyn",
    state: "NY",
    country: "US",
  },
  {
    key: "NYC19",
    name: "Washington Park IV",
    city: "Brooklyn",
    state: "NY",
    country: "US",
  },
  {
    key: "NYC21",
    name: "Yankee Stadium II",
    city: "New York",
    state: "NY",
    country: "US",
  },
  {
    key: "OAK01",
    name: "Oakland-Alameda County Coliseum",
    city: "Oakland",
    state: "CA",
    country: "US",
  },
  {
    key: "PHI03",
    name: "Oakdale Park",
    city: "Philadelphia",
    state: "PA",
    country: "US",
  },
  {
    key: "PIT02",
    name: "Exposition Park I",
    city: "Pittsburgh",
    state: "PA",
    country: "US",
  },
  {
    key: "PRO02",
    name: "Messer Street Grounds",
    city: "Providence",
    state: "RI",
    country: "US",
  },
  {
    key: "RIC02",
    name: "Allens Pasture",
    city: "Richmond",
    state: "VA",
    country: "US",
  },
  {
    key: "SEA02",
    name: "Kingdome",
    city: "Seattle",
    state: "WA",
    country: "US",
  },
  {
    key: "TOR01",
    name: "Exhibition Stadium",
    city: "Toronto",
    state: "ON",
    country: "CA",
  },
  {
    key: "WAS03",
    name: "Capitol Grounds",
    city: "Washington",
    state: "DC",
    country: "US",
  },
  {
    key: "WOR02",
    name: "Agricultural County Fair Grounds II",
    city: "Worcester",
    state: "MA",
    country: "US",
  },
  {
    key: "BAL02",
    name: "Newington Park",
    city: "Baltimore",
    state: "MD",
    country: "US",
  },
  {
    key: "BUF04",
    name: "International Fair Association Grounds",
    city: "Buffalo",
    state: "NY",
    country: "US",
  },
  {
    key: "CHI07",
    name: "South Side Park II",
    city: "Chicago",
    state: "IL",
    country: "US",
  },
  {
    key: "FOR03",
    name: "Jailhouse Flats",
    city: "Fort Wayne",
    state: "IN",
    country: "US",
  },
  {
    key: "HON01",
    name: "Aloha Stadium",
    city: "Honolulu",
    state: "HI",
    country: "US",
  },
  {
    key: "MIN01",
    name: "Athletic Park",
    city: "Minneapolis",
    state: "MN",
    country: "US",
  },
  {
    key: "MIN02",
    name: "Metropolitan Stadium",
    city: "Bloomington",
    state: "MN",
    country: "US",
  },
  {
    key: "PHI09",
    name: "Baker Bowl",
    city: "Philadelphia",
    state: "PA",
    country: "US",
  },
  {
    key: "PIT07",
    name: "Three Rivers Stadium",
    city: "Pittsburgh",
    state: "PA",
    country: "US",
  },
  {
    key: "SAN01",
    name: "Qualcomm Stadium",
    city: "San Diego",
    state: "CA",
    country: "US",
  },
  {
    key: "SFO01",
    name: "Seals Stadium",
    city: "San Francisco",
    state: "CA",
    country: "US",
  },
  {
    key: "SJU01",
    name: "Estadio Hiram Bithorn",
    city: "San Juan",
    state: null,
    country: "PR",
  },
  {
    key: "WNY01",
    name: "West New York Field Club Grounds",
    city: "West New York",
    state: "NJ",
    country: "US",
  },
  {
    key: "ALB01",
    name: "Riverside Park",
    city: "Albany",
    state: "NY",
    country: "US",
  },
  {
    key: "ATL02",
    name: "Turner Field",
    city: "Atlanta",
    state: "GA",
    country: "US",
  },
  {
    key: "BAL09",
    name: "Oriole Park IV",
    city: "Baltimore",
    state: "MD",
    country: "US",
  },
  {
    key: "CIN09",
    name: "Great American Ballpark",
    city: "Cincinnati",
    state: "OH",
    country: "US",
  },
  {
    key: "CLE05",
    name: "League Park III",
    city: "Cleveland",
    state: "OH",
    country: "US",
  },
  {
    key: "CLE08",
    name: "Progressive Field",
    city: "Cleveland",
    state: "OH",
    country: "US",
  },
  {
    key: "COL03",
    name: "Neil Park I",
    city: "Columbus",
    state: "OH",
    country: "US",
  },
  {
    key: "ELM01",
    name: "Maple Avenue Driving Park",
    city: "Elmira",
    state: "NY",
    country: "US",
  },
  {
    key: "IRO01",
    name: "Windsor Beach",
    city: "Irondequoit",
    state: "NY",
    country: "US",
  },
  {
    key: "KAN04",
    name: "Gordon and Koppel Field",
    city: "Kansas City",
    state: "MO",
    country: "US",
  },
  {
    key: "PIT05",
    name: "Exposition Park III",
    city: "Pittsburgh",
    state: "PA",
    country: "US",
  },
  {
    key: "RCK01",
    name: "Agricultural Society Fair Grounds",
    city: "Rockford",
    state: "IL",
    country: "US",
  },
  {
    key: "SAN02",
    name: "PETCO Park",
    city: "San Diego",
    state: "CA",
    country: "US",
  },
  {
    key: "STL07",
    name: "Sportsman's Park III",
    city: "St. Louis",
    state: "MO",
    country: "US",
  },
  {
    key: "STL09",
    name: "Busch Stadium II",
    city: "St. Louis",
    state: "MO",
    country: "US",
  },
  {
    key: "STL10",
    name: "Busch Stadium III",
    city: "St. Louis",
    state: "MO",
    country: "US",
  },
  {
    key: "TOL04",
    name: "Armory Park",
    city: "Toledo",
    state: "OH",
    country: "US",
  },
  {
    key: "TRO01",
    name: "Haymakers' Grounds",
    city: "Troy",
    state: "NY",
    country: "US",
  },
  {
    key: "BAL04",
    name: "Belair Lot",
    city: "Baltimore",
    state: "MD",
    country: "US",
  },
  {
    key: "ATL03",
    name: "Suntrust Park",
    city: "Atlanta",
    state: "GA",
    country: "US",
  },
  {
    key: "BAL07",
    name: "Oriole Park III",
    city: "Baltimore",
    state: "MD",
    country: "US",
  },
  {
    key: "BAL10",
    name: "Terrapin Park",
    city: "Baltimore",
    state: "MD",
    country: "US",
  },
  {
    key: "CAN02",
    name: "Pastime Park",
    city: "Canton",
    state: "OH",
    country: "US",
  },
  {
    key: "CHI12",
    name: "Guaranteed Rate Field",
    city: "Chicago",
    state: "IL",
    country: "US",
  },
  {
    key: "CIN08",
    name: "Cinergy Field",
    city: "Cincinnati",
    state: "OH",
    country: "US",
  },
  {
    key: "DET02",
    name: "Bennett Park",
    city: "Detroit",
    state: "MI",
    country: "US",
  },
  {
    key: "HOU01",
    name: "Colt Stadium",
    city: "Houston",
    state: "TX",
    country: "US",
  },
  {
    key: "IND06",
    name: "Indianapolis Park",
    city: "Indianapolis",
    state: "IN",
    country: "US",
  },
  {
    key: "KAN01",
    name: "Athletic Park",
    city: "Kansas City",
    state: "MO",
    country: "US",
  },
  {
    key: "LOU03",
    name: "Eclipse Park II",
    city: "Louisville",
    state: "KY",
    country: "US",
  },
  {
    key: "NYC06",
    name: "Metropolitan Park",
    city: "New York",
    state: "NY",
    country: "US",
  },
  {
    key: "NYC15",
    name: "Ebbets Field",
    city: "Brooklyn",
    state: "NY",
    country: "US",
  },
  {
    key: "STP01",
    name: "Tropicana Field",
    city: "St. Petersburg",
    state: "FL",
    country: "US",
  },
  {
    key: "SYR02",
    name: "Star Park II",
    city: "Syracuse",
    state: "NY",
    country: "US",
  },
  {
    key: "SYR03",
    name: "Iron Pier",
    city: "Syracuse",
    state: "NY",
    country: "US",
  },
  {
    key: "WAS01",
    name: "Olympic Grounds",
    city: "Washington",
    state: "DC",
    country: "US",
  },
  {
    key: "WAS02",
    name: "National Grounds",
    city: "Washington",
    state: "DC",
    country: "US",
  },
  {
    key: "WAS07",
    name: "American League Park I",
    city: "Washington",
    state: "DC",
    country: "US",
  },
  {
    key: "BOS02",
    name: "Dartmouth Grounds",
    city: "Boston",
    state: "MA",
    country: "US",
  },
  {
    key: "CHI01",
    name: "Lake Front Park I",
    city: "Chicago",
    state: "IL",
    country: "US",
  },
  {
    key: "CHI02",
    name: "23rd Street Park",
    city: "Chicago",
    state: "IL",
    country: "US",
  },
  {
    key: "CHI03",
    name: "Lake Front Park II",
    city: "Chicago",
    state: "IL",
    country: "US",
  },
  {
    key: "CHI05",
    name: "South Side Park I",
    city: "Chicago",
    state: "IL",
    country: "US",
  },
  {
    key: "CLE07",
    name: "Cleveland Stadium",
    city: "Cleveland",
    state: "OH",
    country: "US",
  },
  {
    key: "CLE09",
    name: "Cedar Avenue Driving Park",
    city: "Cleveland",
    state: "OH",
    country: "US",
  },
  {
    key: "DET04",
    name: "Tiger Stadium",
    city: "Detroit",
    state: "MI",
    country: "US",
  },
  {
    key: "GEA01",
    name: "Geauga Lake Grounds",
    city: "Geauga Lake",
    state: "OH",
    country: "US",
  },
  {
    key: "HOU02",
    name: "Astrodome",
    city: "Houston",
    state: "TX",
    country: "US",
  },
  {
    key: "JER01",
    name: "Oakdale Park",
    city: "Jersey City",
    state: "NJ",
    country: "US",
  },
  {
    key: "JER02",
    name: "Roosevelt Stadium",
    city: "Jersey City",
    state: "NJ",
    country: "US",
  },
  {
    key: "KAN06",
    name: "Kauffman Stadium",
    city: "Kansas City",
    state: "MO",
    country: "US",
  },
  {
    key: "LBV01",
    name: "The Ballpark at Disney's Wide World",
    city: "Lake Buena Vista",
    state: "FL",
    country: "US",
  },
  {
    key: "MID01",
    name: "Mansfield Club Grounds",
    city: "Middletown",
    state: "CT",
    country: "US",
  },
  {
    key: "NYC16",
    name: "Yankee Stadium I",
    city: "New York",
    state: "NY",
    country: "US",
  },
  {
    key: "PHI01",
    name: "Jefferson Street Grounds",
    city: "Philadelphia",
    state: "PA",
    country: "US",
  },
  {
    key: "ROC03",
    name: "Ontario Beach Grounds",
    city: "Rochester",
    state: "NY",
    country: "US",
  },
  {
    key: "SEA01",
    name: "Sick's Stadium",
    city: "Seattle",
    state: "WA",
    country: "US",
  },
  {
    key: "SFO02",
    name: "Candlestick Park",
    city: "San Francisco",
    state: "CA",
    country: "US",
  },
  {
    key: "SPR01",
    name: "Hampden Park Race Track",
    city: "Springfield",
    state: "MA",
    country: "US",
  },
  {
    key: "STL01",
    name: "Red Stockings Base Ball Park",
    city: "St. Louis",
    state: "MO",
    country: "US",
  },
  {
    key: "STL05",
    name: "Robison Field",
    city: "St. Louis",
    state: "MO",
    country: "US",
  },
  {
    key: "WAT01",
    name: "Troy Ball Club Grounds",
    city: "Watervliet",
    state: "NY",
    country: "US",
  },
  {
    key: "WAV01",
    name: "Waverly Fairgrounds",
    city: "Waverly",
    state: "NJ",
    country: "US",
  },
  {
    key: "WOR01",
    name: "Agricultural County Fair Grounds I",
    city: "Worcester",
    state: "MA",
    country: "US",
  },
  {
    key: "WOR03",
    name: "Worcester Driving Park Grounds",
    city: "Worcester",
    state: "MA",
    country: "US",
  },
  {
    key: "BAL12",
    name: "Oriole Park at Camden Yards",
    city: "Baltimore",
    state: "MD",
    country: "US",
  },
  {
    key: "BUF01",
    name: "Riverside Grounds",
    city: "Buffalo",
    state: "NY",
    country: "US",
  },
  {
    key: "BUF02",
    name: "Olympic Park I",
    city: "Buffalo",
    state: "NY",
    country: "US",
  },
  {
    key: "KAN05",
    name: "Municipal Stadium",
    city: "Kansas City",
    state: "MO",
    country: "US",
  },
  {
    key: "NYC12",
    name: "Washington Park III",
    city: "Brooklyn",
    state: "NY",
    country: "US",
  },
  {
    key: "NYC18",
    name: "Wallace's Ridgewood Park",
    city: "Queens",
    state: "NY",
    country: "US",
  },
  {
    key: "ROC01",
    name: "Culver Field I",
    city: "Rochester",
    state: "NY",
    country: "US",
  },
  {
    key: "STL02",
    name: "Grand Avenue Park",
    city: "St. Louis",
    state: "MO",
    country: "US",
  },
  {
    key: "STL03",
    name: "Sportsman's Park I",
    city: "St. Louis",
    state: "MO",
    country: "US",
  },
  {
    key: "TOL03",
    name: "Speranza Park",
    city: "Toledo",
    state: "OH",
    country: "US",
  },
  {
    key: "TRO02",
    name: "Putnam Grounds",
    city: "Troy",
    state: "NY",
    country: "US",
  },
  {
    key: "ATL01",
    name: "Atlanta-Fulton County Stadium",
    city: "Atlanta",
    state: "GA",
    country: "US",
  },
  {
    key: "CHI08",
    name: "West Side Grounds",
    city: "Chicago",
    state: "IL",
    country: "US",
  },
  {
    key: "DOV01",
    name: "Fairview Park Fair Grounds",
    city: "Dover",
    state: "DE",
    country: "US",
  },
  {
    key: "HOU03",
    name: "Minute Maid Park",
    city: "Houston",
    state: "TX",
    country: "US",
  },
  {
    key: "KAN02",
    name: "Association Park",
    city: "Kansas City",
    state: "MO",
    country: "US",
  },
  {
    key: "MAS01",
    name: "Long Island Grounds",
    city: "Maspeth",
    state: "NY",
    country: "US",
  },
  {
    key: "NYC17",
    name: "Shea Stadium",
    city: "New York",
    state: "NY",
    country: "US",
  },
  {
    key: "RIC01",
    name: "Richmond Fair Grounds",
    city: "Richmond",
    state: "VA",
    country: "US",
  },
  {
    key: "SEA03",
    name: "Safeco Field",
    city: "Seattle",
    state: "WA",
    country: "US",
  },
  {
    key: "TOL01",
    name: "League Park",
    city: "Toledo",
    state: "OH",
    country: "US",
  },
  {
    key: "WAS10",
    name: "Robert F. Kennedy Stadium",
    city: "Washington",
    state: "DC",
    country: "US",
  },
];

const resolvers = {
  Park: {
    __resolveReference(reference) {
      return parks.find((park) => park.key === reference.key);
    },
  },
  Query: {
    viewer(parent, args, { user }) {
      return parks[0];
    },
  },
};

export default resolvers;
